export interface Currencies {
  USD: CurrencyData;
  CAD: CurrencyData;
  EUR: CurrencyData;
  AED: CurrencyData;
  AFN: CurrencyData;
  ALL: CurrencyData;
  AMD: CurrencyData;
  ARS: CurrencyData;
  AUD: CurrencyData;
  AZN: CurrencyData;
  BAM: CurrencyData;
  BDT: CurrencyData;
  BGN: CurrencyData;
  BHD: CurrencyData;
  BIF: CurrencyData;
  BND: CurrencyData;
  BOB: CurrencyData;
  BRL: CurrencyData;
  BWP: CurrencyData;
  BYN: CurrencyData;
  BZD: CurrencyData;
  CDF: CurrencyData;
  CHF: CurrencyData;
  CLP: CurrencyData;
  CNY: CurrencyData;
  COP: CurrencyData;
  CRC: CurrencyData;
  CVE: CurrencyData;
  CZK: CurrencyData;
  DJF: CurrencyData;
  DKK: CurrencyData;
  DOP: CurrencyData;
  DZD: CurrencyData;
  EEK: CurrencyData;
  EGP: CurrencyData;
  ERN: CurrencyData;
  ETB: CurrencyData;
  GBP: CurrencyData;
  GEL: CurrencyData;
  GHS: CurrencyData;
  GNF: CurrencyData;
  GTQ: CurrencyData;
  HKD: CurrencyData;
  HNL: CurrencyData;
  HRK: CurrencyData;
  HUF: CurrencyData;
  IDR: CurrencyData;
  ILS: CurrencyData;
  INR: CurrencyData;
  IQD: CurrencyData;
  IRR: CurrencyData;
  ISK: CurrencyData;
  JMD: CurrencyData;
  JOD: CurrencyData;
  JPY: CurrencyData;
  KES: CurrencyData;
  KHR: CurrencyData;
  KMF: CurrencyData;
  KRW: CurrencyData;
  KWD: CurrencyData;
  KZT: CurrencyData;
  LBP: CurrencyData;
  LKR: CurrencyData;
  LTL: CurrencyData;
  LVL: CurrencyData;
  LYD: CurrencyData;
  MAD: CurrencyData;
  MDL: CurrencyData;
  MGA: CurrencyData;
  MKD: CurrencyData;
  MMK: CurrencyData;
  MOP: CurrencyData;
  MUR: CurrencyData;
  MXN: CurrencyData;
  MYR: CurrencyData;
  MZN: CurrencyData;
  NAD: CurrencyData;
  NGN: CurrencyData;
  NIO: CurrencyData;
  NOK: CurrencyData;
  NPR: CurrencyData;
  NZD: CurrencyData;
  OMR: CurrencyData;
  PAB: CurrencyData;
  PEN: CurrencyData;
  PHP: CurrencyData;
  PKR: CurrencyData;
  PLN: CurrencyData;
  PYG: CurrencyData;
  QAR: CurrencyData;
  RON: CurrencyData;
  RSD: CurrencyData;
  RUB: CurrencyData;
  RWF: CurrencyData;
  SAR: CurrencyData;
  SDG: CurrencyData;
  SEK: CurrencyData;
  SGD: CurrencyData;
  SOS: CurrencyData;
  SYP: CurrencyData;
  THB: CurrencyData;
  TND: CurrencyData;
  TOP: CurrencyData;
  TRY: CurrencyData;
  TTD: CurrencyData;
  TWD: CurrencyData;
  TZS: CurrencyData;
  UAH: CurrencyData;
  UGX: CurrencyData;
  UYU: CurrencyData;
  UZS: CurrencyData;
  VEF: CurrencyData;
  VND: CurrencyData;
  XAF: CurrencyData;
  XOF: CurrencyData;
  YER: CurrencyData;
  ZAR: CurrencyData;
  ZMK: CurrencyData;
  ZWL: CurrencyData;
}

export interface CurrencyData {
  symbol: string;
  name: string;
  symbol_native: string;
  decimal_digits: number;
  rounding: number;
  code: string;
  name_plural: string;
}

export type CountryCode =
  | "USD"
  | "CAD"
  | "EUR"
  | "AED"
  | "AFN"
  | "ALL"
  | "AMD"
  | "ARS"
  | "AUD"
  | "AZN"
  | "BAM"
  | "BDT"
  | "BGN"
  | "BHD"
  | "BIF"
  | "BND"
  | "BOB"
  | "BRL"
  | "BWP"
  | "BYN"
  | "BZD"
  | "CDF"
  | "CHF"
  | "CLP"
  | "CNY"
  | "COP"
  | "CRC"
  | "CVE"
  | "CZK"
  | "DJF"
  | "DKK"
  | "DOP"
  | "DZD"
  | "EEK"
  | "EGP"
  | "ERN"
  | "ETB"
  | "GBP"
  | "GEL"
  | "GHS"
  | "GNF"
  | "GTQ"
  | "HKD"
  | "HNL"
  | "HRK"
  | "HUF"
  | "IDR"
  | "ILS"
  | "INR"
  | "IQD"
  | "IRR"
  | "ISK"
  | "JMD"
  | "JOD"
  | "JPY"
  | "KES"
  | "KHR"
  | "KMF"
  | "KRW"
  | "KWD"
  | "KZT"
  | "LBP"
  | "LKR"
  | "LTL"
  | "LVL"
  | "LYD"
  | "MAD"
  | "MDL"
  | "MGA"
  | "MKD"
  | "MMK"
  | "MOP"
  | "MUR"
  | "MXN"
  | "MYR"
  | "MZN"
  | "NAD"
  | "NGN"
  | "NIO"
  | "NOK"
  | "NPR"
  | "NZD"
  | "OMR"
  | "PAB"
  | "PEN"
  | "PHP"
  | "PKR"
  | "PLN"
  | "PYG"
  | "QAR"
  | "RON"
  | "RSD"
  | "RUB"
  | "RWF"
  | "SAR"
  | "SDG"
  | "SEK"
  | "SGD"
  | "SOS"
  | "SYP"
  | "THB"
  | "TND"
  | "TOP"
  | "TRY"
  | "TTD"
  | "TWD"
  | "TZS"
  | "UAH"
  | "UGX"
  | "UYU"
  | "UZS"
  | "VEF"
  | "VND"
  | "XAF"
  | "XOF"
  | "YER"
  | "ZAR"
  | "ZMK"
  | "ZWL";
